config/routes.rb
Rails.application.routes.draw do
  get 'search/google', to: 'search#google'

  devise_for :users

  get 'home/about'
  root 'home#index'
  get "home/friends"
  resources :friends
  get 'projects', to: 'portfolio#index', as: 'projects'
  get 'services', to: 'social#index', as: 'services'
  get 'about', to: 'contact#index', as: 'about'
  get 'contact', to: 'static_pages#namie', as: 'contact'

  get 'builds/:build_id', to: 'builds#show', as: 'build'





  # config/routes.rb
post 'transcribe_audio', to: 'transcriptions#create'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/builds_controller.rb
# app/controllers/builds_controller.rb

class BuildsController < ApplicationController
    def show
      @build_id = params[:build_id].to_s
    end
  end
  

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is William Francis."
  end

end

app/controllers/minorprojects_controller.rb
class MinorprojectsController < ApplicationController
    def index
    end
  end
  

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
    def index
    end
  end
  

app/controllers/search_controller.rb
# app/controllers/search_controller.rb
class SearchController < ApplicationController
    def google
        query = params[:query]
        search_engine_id = "a6ccd2b24e9284464"
        encoded_query = CGI.escape(query)
        redirect_url = "https://cse.google.com/cse?cx=#{search_engine_id}&q=#{encoded_query}"
        redirect_to redirect_url, allow_other_host: true
    rescue => e
        logger.error e.message
        logger.error e.backtrace.join("\n")
        render plain: "An error occurred: #{e.message}", status: 500
    end
end

app/controllers/social_controller.rb
class SocialController < ApplicationController
    def index
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def namie
      # This action will render the privacy policy page.
    end
  end
  

app/controllers/transcriptions_controller.rb
# app/controllers/transcriptions_controller.rb

class TranscriptionsController < ApplicationController
    skip_before_action :verify_authenticity_token # Skip CSRF check for API
  
    def create
      puts "Received request for transcription"
  
      audio_file = params[:audio]
      puts "Audio file: #{audio_file.inspect}"
  
      client = OpenAI::Client.new  # Initializes the OpenAI client
  
      # Transcribe audio using the 'whisper-1' model
      response = client.audio.transcribe(
        parameters: {
          model: "whisper-1",
          file: audio_file.tempfile
        }
      )
  
      puts "Whisper API response: #{response['text']}"
  
      # You can now send this response to your iOS app as a note.
      if response["text"].present?
        render json: { transcription: response["text"] }, status: :ok
      else
        puts "Failed to transcribe audio"
        render json: { error: 'Failed to transcribe audio' }, status: :bad_request
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/social_helper.rb
module SocialHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transcriptions_helper.rb
module TranscriptionsHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>William Francis Misiaszek</title>
    <link rel="stylesheet" href="/assets/application.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    <style>

    /* Content container should not overlap the TOC container */
.content-container {
    margin-right: 250px; /* or more, depending on the actual width of the TOC container */
}

/* Ensure the right-hand side recipe widget has fixed width */
.toc-container {
    width: 200px; /* Adjust the width as needed */
    position: fixed;
    right: 0;
    top: 100px;
}

/* Ensure the blog post itself has padding and possibly a max-width to prevent overflow */
.blog-post {
    padding: 20px; /* This adds padding all around the post */
    margin-bottom: 20px; /* This adds space below each post */
    max-width: calc(100% - 220px); /* Example calculation to prevent overflow */
    background: #fff; /* Assuming you want a white background */
    box-shadow: 0 2px 4px rgba(0,0,0,0.1); /* Optional: Adds a subtle shadow for depth */
}



    /* Adjusting header sizes */
h1, h2, h3 {
    font-size: 1.7rem; /* Adjust the size as needed */
    margin-bottom: 0.5rem;
}

/* List styles */
ol, ul {
    padding-left: 40px; /* Increase indentation of list */
    margin-bottom: 10px; /* Space below the list */
}

li {
    margin-bottom: 10px; /* Space between list items */
    line-height: 1.6; /* Improve readability */
    font-size: 1rem; /* Adjust the font size as needed */
}

/* Ordered list specific styles */
ol {
    counter-reset: item;
    list-style-type: none;
}

ol li {
    counter-increment: item;
    position: relative;
}

ol li:before {
    content: counter(item) ". ";
    position: absolute;
    left: -30px; /* Adjust based on actual padding-left of ol */
    font-weight: bold; /* Make numbers bold */
}

/* Spacing for additional images */
.additional-images {
    margin-top: 10px; /* This adds space between the main image and additional images */
}
        body { font-family: Arial, sans-serif; }
        .toc-container { position: fixed; right: 20px; top: 100px; width: 200px; }
        .toc-dropdown { list-style: none; padding: 0; margin: 0; }
        .toc-dropdown li { margin-bottom: 10px; }
        .toc-link { text-decoration: none; color: #004085; }
        .content-container { margin-right: 250px; }
        .blog-image { width: 100%; height: auto; }
        .additional-images img { cursor: pointer; width: 30%; margin-right: 5%; }
        .secondary-image {
    max-width: 200px;
    margin-right: 20px;
    padding: 10px; /* Adds padding around the image */
    background-color: #fff; /* Optional: Adds a white background around the image */
    box-shadow: 0 2px 4px rgba(0,0,0,0.1); /* Optional: Adds a subtle shadow for depth */
}
    </style>
</head>
<body>
    <div class="container mt-2 pb-5">
        <h1 class="animate__animated animate__fadeInDown" style="color: #004085;">Food Blog</h1>


            <div id="steak1" class="blog-post">
                <h2>Steak Salad</h2>
                <!-- Main Image -->
                <%= link_to image_tag("food/steak1.jpeg", alt: "Main Steak Salad", class: "img-fluid", style: "max-width: 20%;"), asset_path("food/steak1.jpeg"), target: "_blank" %>
                <h3>Main:</h3>
                <ul>
                    <li>Steak</li>
                    <li>Egg</li>
                    <li>Butter (Olive Oil good too)</li>
                </ul>
                <h3>Salad:</h3>
                <ul>
                    <li>Mixed Greens (50/50, Arugula good too)</li>
                    <li>Mini Tomatoes</li>
                    <li>Mandarins</li>
                    <li>Greek Yogurt (0% or 2%)</li>
                    <li>Sweet Potatoes</li>
                </ul>
                <h3>Spices:</h3>
                <ul>
                    <li>Basil</li>
                    <li>Oregano</li>
                    <li>TJ’s Green Goddess</li>
                    <li>Timut Pepper</li>
                </ul>
                <ol>
                    <li>Pre-heat oven to 350, insert auto-thermometer set to 117F. Craft salad while steak reaches internal temperature (20 minutes).</li>
                    <li>Prep pan at ultra high temp (8-10) to finish our reverse seared steak. Add butter and turn on pan as steak gets close to 117F. Optionally have 2nd pan for egg started too.</li>
                    <li>For potatoes, stab with fork on the top and bottom 2-3 times, put in bowl, add a splash of water, and put in microwave for 5-6 minutes. Optionally cut and place on salad.</li>
                    <li>Pull Steak out of oven, sear top and bottom for 20-30 seconds (your preference here). Top salad off with Steak and Egg.</li>
                </ol>
                <div class="additional-images">
                    <%= link_to image_tag("food/steak2.jpeg", alt: "Additional Image 1", class: "img-fluid secondary-image", style: "max-width: 150px; margin-right: 20px;"), asset_path("food/steak2.jpeg"), target: "_blank" %>
                    <%= link_to image_tag("food/steak3.jpeg", alt: "Additional Image 2", class: "img-fluid secondary-image", style: "max-width: 130px; margin-right: 20px;"), asset_path("food/steak3.jpeg"), target: "_blank" %>
                </div>
            </div>

     <div id="tacos1" class="blog-post">
                        <h2>Super Tacos</h2>
                        <!-- Main Image -->
                        <%= link_to image_tag("food/tacos1.jpeg", alt: "Main Tacos", class: "img-fluid", style: "max-width: 40%;"), asset_path("food/tacos1.jpeg"), target: "_blank" %>
                        <h3>Main:</h3>
            <ul>
                <li>Meat (96/4 Beef)</li>
                <li>Egg</li>
                <li>Olive Oil</li>
                <li>Whole Wheat Pita (Sonoran Style/Any Tortilla)</li>
            </ul>
            <h3>Fixings:</h3>
            <ul>
                <li>Cilantro (50/50, Arugula good too)</li>
                <li>Mini Tomatoes</li>
                <li>Mandarins</li>
                <li>Greek Yogurt (0% or 2%)</li>
                <li>Mini Avocado</li>
            </ul>
            <h3>Spices/Sauces:</h3>
            <ul>
                <li>Basil</li>
                <li>Oregano</li>
                <li>Fav Hot Sauce (Sabatino Truffle)</li>
                <li>Timut Pepper</li>
            </ul>
            <ol>
<li>Heat Pan (5-7) with Olive Oil. Add Protein with Spices and close lid to cook slowly while prepping fixings. Turn meat to other side when ready (clean blood release).</li>
<li>Cut and Prep Fixings into separate bowls: Tomatoes/Mandarins, Avocado, Yogurt, Cilantro/Arugula. </li>
<li>Put meat in serving dish, set aside to finish tortillas on same pan.</li>
<li>Defrost tortilla/pita for 60 seconds with tortilla warmer. Finish off on pan with a dab of olive oil, and put back into tortilla holder. Optional to have egg pan on too for eggs.</li>
</ol>
<div class="additional-images">
                    <%= link_to image_tag("food/tacos2.jpeg", alt: "Additional Image 1", class: "img-fluid secondary-image", style: "max-width: 150px; margin-right: 20px;"), asset_path("food/tacos2.jpeg"), target: "_blank" %>
                </div>

        </div>          

            <!-- Table of Contents -->
            <div class="col-lg-4">
                <div class="toc-container">
                    <h4>Recipes</h4>
                    <ul class="toc-dropdown">
                        <!-- Dynamically filled by JavaScript/jQuery -->
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    
    <script>
        $(document).ready(function() {
            const recipes = [
                { title: "Steak Salad", date: "2023-04-02", id: "steak1" },
                { title: "Super Tacos", date: "2023-04-01", id: "tacos1" },
                // Add your recipes here
            ];

            recipes.forEach(function(recipe) {
                $('.toc-dropdown').append(
                    `<li><a href="#${recipe.id}" class="toc-link">${recipe.title} - ${recipe.date}</a></li>`
                );
            });
        });

        function showImageModal(src) {
            // Set the src of the modal image to the src of the clicked image
            $('#modalImage').attr('src', src);
            // Show the modal
            $('#imageModal').modal('show');
        }
    </script>
</body>
</html>

app/views/home/_header.html.erb
<head>
  <style>
  .navbar-collapse {
    background-color: #000000;
}

.logo-container {
  height: 70px;
    background-color: #F8F8F8;
    padding: 5px; /* Adjusted from 10px to 5px */
    display: flex;
    align-items: center;
    flex-direction: row; /* Adjusted from column to row */
      margin-left: -10px; /* Added this line */

  }
  
  .logo-container .avatar {
    margin-right: 10px; /* Add a little space between the avatar and the text */
    transform: scale(0.85); /* Reduce size by 15% */

  }





@media (max-width: 768px) {

.slide-in {
  animation: slide-in 0.5s forwards;
}

.slide-out {
  animation: slide-out 0.5s forwards;
}

@keyframes slide-in {
  0% { transform: translateY(-100%); }
  100% { transform: translateY(0); }
}

@keyframes slide-out {
  0% { transform: translateY(0); }
  100% { transform: translateY(-100%); }
}
    .logo-container .logo {
        width: 25px; /* Adjusted from 35px to 25px */
        height: 25px; /* Adjusted from 35px to 25px */
    }

    .logo-container {
    height: 70px;
    background-color: #F8F8F8;
    padding: 5px; /* Adjusted from 10px to 5px */
    display: flex;
    align-items: center;
    flex-direction: row; /* Adjusted from column to row */
    margin-left: -10px; /* Added this line */
    margin-top: -8px;

  }
  

  .navbar-collapse {
        background-color: #000000;
    }
  }

    @keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.spin {
  animation: spin 2s linear;
}

.nav-link:hover i {
  transform: scale(1.17);
  transition: transform 0.3s ease-in-out;
}



  </style>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #000000;">
<div class="logo-container">
<div class="avatar" style="cursor: pointer; border: 3px solid white; border-radius: 50%;" onclick="location.href='<%= root_path %>'">
    <%= image_tag "profilepic.jpg", class: "logo", width: '35', height: '20', style: 'border-radius: 15%;' %>
</div>

<div class="name-and-icons">
    <%= link_to "William Francis", root_path, class: "navbar-brand spacing-nav", style: "color: black; align-self: center;" %>
    <div class="social-media-icons">
    <%= link_to '<i class="fab fa-twitter icon-spin-on-click"></i>'.html_safe, "https://twitter.com/willyumfrancis", class: "nav-link" %>

    <%= link_to '<i class="fab fa-linkedin icon-spin-on-click"></i>'.html_safe, "https://www.linkedin.com/in/williamfrancismisiaszek/", class: "nav-link" %>
<%= link_to '<i class="fab fa-instagram icon-spin-on-click"></i>'.html_safe, "https://www.instagram.com/wfteddybear/", class: "nav-link" %>
<%= link_to '<i class="fab fa-tiktok icon-spin-on-click"></i>'.html_safe, "https://www.tiktok.com/@beszos?lang=en", class: "nav-link" %>

        </div>
</div>
</div>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav">

  <li class="nav-item <%= 'active' if current_page?(portfolio_path) %>">
    <%= link_to "Tech", portfolio_path, class:"nav-link" %>
  </li>
  <li class="nav-item <%= 'active' if current_page?(social_path) %>">
    <%= link_to "Music", social_path, class:"nav-link" %>
  </li>
  <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
  <%= link_to "Healthy Recipes", contact_path, class:"nav-link" %>
</li>

</ul>
      <div class="ml-auto">
  <%= form_tag search_google_path, method: :get, class: 'form-inline my-2 my-lg-0' do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Search', class: 'form-control mr-sm-2', 'aria-label': 'Search' %>
    <%= submit_tag 'Search', class: 'btn btn-outline-light my-2 my-sm-0', name: nil %>
  <% end %>
</div>

    
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script>
$(document).ready(function(){
  $(".icon-spin-on-click").click(function(){
    $(this).addClass("spin");
  });
});


  document.addEventListener("DOMContentLoaded", () => {
    if (window.matchMedia("(min-width: 768px)").matches) {
      const header = document.querySelector("nav.navbar.sticky-top");

      let previousScroll = window.pageYOffset;

      window.addEventListener("wheel", (event) => {
        const deltaY = event.deltaY;
        const currentScroll = window.pageYOffset;

        if (currentScroll === 0) {
          // At top of page, slide in header
          header.classList.remove("slide-out");
          header.classList.add("slide-in");
        } else if (deltaY < -10) {
          // Scrolling up is negative deltaY
          header.classList.remove("slide-out");
          header.classList.add("slide-in");
        } else if (deltaY > 10) {
          // Scrolling down is positive deltaY
          header.classList.remove("slide-in");
          header.classList.add("slide-out");
        }

        previousScroll = currentScroll;
      });
    }
  });
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>



</body>

app/views/home/about.html.erb
<h1> About Us </h1>

<%= @about_me %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>William Francis Misiaszek | Technical Product Manager</title>

    <!-- Bootstrap CSS -->
    <!-- Animate.css for animations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="/assets/application.css">
</head>

<body>
    <div class="container mt-2 pb-5">
        <!-- Debugging print statement: Main container -->

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <!-- About Me -->
                <h2 class="display-9 animate__animated animate__fadeIn"><strong>About Me</strong></h2>
                <!-- Debugging print statement: About Me -->
                <p class="lead animate__animated animate__fadeIn">
                    As a Technical Product Manager with a foundation in Swift, Ruby, and Javascript, I am driven by operational efficiency and the quest for innovation. My journey has been marked by successful user growth strategies, cost management, and effective global team coordination.
                </p>

                <!-- Skills -->
                <h2 class="display-9 animate__animated animate__fadeIn"><strong>Skills</strong></h2>
                <!-- Debugging print statement: Skills -->
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item">Programming: Swift, Ruby, Javascript</li>
                    <li class="list-group-item">Tools: Figma, JIRA, Notion, GA4/UA</li>
                    <li class="list-group-item">Languages: English, Spanish</li>
                </ul>

                <!-- Experience -->
                <h2 class="my-3 display-9 animate__animated animate__fadeIn"><strong>Experience</strong></h2>
                <!-- Debugging print statement: Experience -->
                <!-- Technical Product Manager - Stanford University -->
                <h3 class="lead animate__animated animate__fadeIn" style="font-weight: bold;">Technical Product Manager - Stanford University (06/2022—Present)</h3>
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item">Strategic Product Development: Spearheaded the redesign of STANFORD Magazine's website, achieving a 15% YoY growth in user engagement by integrating JavaScript, dynamic headers, and interactive maps.</li>
                    <li class="list-group-item">Data-Driven Decision Making: Utilized Google Analytics for insightful user engagement analysis, driving product direction with a focus on metrics and performance.</li>
                    <li class="list-group-item">Global Team Management & Cost Efficiency: Coordinated with international teams in Colombia, enhancing team productivity by 30%; Reduced engineering costs by 75% through strategic resource planning.</li>
                </ul>
                <!-- Associate Product Manager - Stanford University -->
                <h3 class="lead animate__animated animate__fadeIn" style="font-weight: bold;">Associate Product Manager - Stanford University (09/2021—06/2022)</h3>
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item">Technical Project Synchronization: Aligned technical projects with the university's financial cycles, optimizing budget utilization for efficient project delivery.</li>
                </ul>
                <!-- Systems Analyst - Stanford University -->
                <h3 class="lead animate__animated animate__fadeIn" style="font-weight: bold;">Systems Analyst - Stanford University (01/2020—11/2021)</h3>
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item">Product Ownership & Enhancement: Product Owner for key systems, enhancing the Graduate Financial System and Cardinal Print Application, benefiting over 20,000 students.</li>
                </ul>
                
                <!-- Projects -->
                <h2 class="my-3 display-9 animate__animated animate__fadeIn"><strong>Projects</strong></h2>
                <!-- Debugging print statement: Projects -->
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item"><a href="https://www.poliscope.org" target="_blank">PoliScope - AI Bill Analyzer</a>: Uses LLM+LangChain for sentiment analysis and integrated data from multiple sources such as Legistar and OpenData.</li>
                    <li class="list-group-item"><a href="https://testflight.apple.com/join/rIyScvls" target="_blank">Namie - iOS Application</a>: Developed an iOS app using Swift, focusing on user experience by providing geolocation-based reminders for enhancing personal connections in community settings.</li>
                </ul>
                
                <!-- Education -->
                <h2 class="display-9 animate__animated animate__fadeIn"><strong>Education</strong></h2>
                <!-- Debugging print statement: Education -->
                <ul class="list-group list-group-flush animate__animated animate__fadeIn">
                    <li class="list-group-item">Google | Data Analytics ’21</li>
                    <li class="list-group-item">PMI | Project Management ’21</li>
                    <li class="list-group-item">UC San Diego | BA Economics ’18</li>
                </ul>
                
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>

</html>

app/views/portfolio/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Portfolio - William Francis Misiaszek</title>

    <!-- Animate.css for animations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="/assets/application.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<style>

.row {
    display: flex;
    justify-content: center; /* This will horizontally center the items */
}

.col-md-6 {
    display: flex;
    justify-content: center; /* This centers the content of the column */
    margin-bottom: 4rem; /* Adjust the bottom margin as needed */
}

.img-fluid {
    max-width: 100%;
    height: auto;
    margin: auto; /* This will apply automatic margins on all sides, centering the image */
}


</style>

<body>
    <div class="container mt-2 pb-5">
        <h1 class="text-center mb-3 animate__animated animate__fadeInDown" style="color: #004085;">Friendly Neighbor</h1>

        <!-- Your existing sections here -->

        <!-- Image Gallery Section -->
        <div class="row justify-content-center mt-4 animate__animated animate__fadeIn">
            <h2 class="text-center w-100">Project Gallery</h2>
            <!-- Images with dynamic path helpers -->
            <% (1..6).each do |i| %>
            <div class="col-md-6 mb-4">
                <a href="<%= build_path(build_id: i) %>">
                    <%= image_tag "build#{i}.jpg", alt: "Project #{i}", class: "img-fluid" %>
                </a>
            </div>
            <% end %>
        </div>

        <!-- Bootstrap JS and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    </div>
</body>

</html>